name: CI/CD

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login docker hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CUSTOM_DOCKER_HUB }}
          username: ${{ secrets.CUSTOM_DOCKER_USERNAME }}
          password: ${{ secrets.CUSTOM_DOCKER_TOKEN }}
      - name: get docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gotoo123/just4u-backend
      - name: docker-build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.CUSTOM_DOCKER_HUB }}/gotoo123/just4u-backend:main
          label: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop just4u-backend
            docker rm just4u-backend
            docker rmi gotoo123/just4u-backend:main
            docker pull ${{ secrets.CUSTOM_DOCKER_HUB }}/gotoo123/just4u-backend:main
            docker run --name just4u-backend -d -p 8888:3000 -v /gotoo/data:/app/server/data ${{ secrets.CUSTOM_DOCKER_HUB }}/gotoo123/just4u-backend:main
